f = "GAGGTTGTCCGGACCTGCGTTGATTAGTATCACGGTCGAGCTTGGAAACCAGGTTTTCCCTCTGCCGGGGGTTGCACCGTCCTGTCTTTCCTAGAGTATCCACCCCGAAGTGAAGACAATCATTAGCATCCGACTCTGAAGCGAAGCACTGTACTACAATCCACCGTACCCACCCCATGAGCCAGAAGTAATCATCTGTACGCACTCCAGGCCGGTGCATGTGGGTGCCGCTAAGGCTGTCCACTTATAGAAGAAATTTGCTCGGTCTATTAACCCGTACCGGCTAAGATTAAAACTTAAGTTTGACTGTATTCCTTCGACTGTGGTAAGACCGCATGATTTGCTACCTGCAAAAGGCTCTTCTAAGCGACGGGAAACCATCCAAACCTCTGGTTAATAGCCTGACAGCGAGAGAGTACTTAAGTTGATGGAGACCAGGGACGTGACGTGCGGGTGTGGTCGGCTCTAGCAACATCCCATTCAACTTGGTTCTCTTTGTCCATAAGCTTTTACGAAAATTAGAGACTATAAGAGACCGTAGGAGTGTCAGCTCATCTTTCCGAACGCGCAGTGGCGAGCGCGAAGAAAGGCAGCGACCACAAACTCTTGACATTCAGGGCGACTACCCTACAGCGCCTCGGACATGCTGGACCGCGTATAACGCATTACTGCTTGATCATTAGAGCCCGCGTATTCCGTAAATGTCCCGTACAATAGCGTGTCCTCTATCTGGAGCGTTAGAGAGCTAGTGGCCATCGCTCTCATGGTATTTGACTGGGAACGGTTCAGCCTGGTTGCATTGCGGGACACCGGCGAT"
nuct = {'A' : 0,
        'C' : 0,
        'G' : 0,
        'T' : 0}
print(f)
for i in f:
    if i == "\\n" or i == "n":
        exit
    print(i)
    nuct[i] += 1 

print(nuct['A'],nuct['C'],nuct['G'],nuct['T'])
    
